In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
#if tensorflow<2.0 version
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:

sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:

### Vocabulary size
voc_size=10000

In [7]:
##one hot representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[6690, 1308, 9467, 451], [6690, 1308, 9467, 4281], [6690, 8118, 9467, 4380], [3555, 2607, 4760, 2382, 9431], [3555, 2607, 4760, 2382, 7401], [9032, 6690, 8455, 9467, 9248], [900, 4726, 9289, 2382]]


In [8]:
##Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:

sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6690 1308 9467  451]
 [   0    0    0    0 6690 1308 9467 4281]
 [   0    0    0    0 6690 8118 9467 4380]
 [   0    0    0 3555 2607 4760 2382 9431]
 [   0    0    0 3555 2607 4760 2382 7401]
 [   0    0    0 9032 6690 8455 9467 9248]
 [   0    0    0    0  900 4726 9289 2382]]


In [12]:
dim=10

In [13]:

model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:

model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775
   -0.0264017  -0.04175306  0.03438387  0.00483886 -0.01813291]
  [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775
   -0.0264017  -0.04175306  0.03438387  0.00483886 -0.01813291]
  [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775
   -0.0264017  -0.04175306  0.03438387  0.00483886 -0.01813291]
  [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775
   -0.0264017  -0.04175306  0.03438387  0.00483886 -0.01813291]
  [-0.04918884  0.03701763 -0.00412145 -0.01944529  0.04716099
    0.039835   -0.01221706 -0.00536225 -0.00781418  0.03370618]
  [-0.0365024  -0.04171776  0.03433042  0.00960976  0.01449699
    0.04940602  0.00861019  0.0392453  -0.00889333 -0.02117573]
  [ 0.00409447 -0.02808121  0.02859398 -0.01169022 -0.02417239
   -0.00847627  0.0374534   0.01881081  0.04700155  0.01323311]
  [ 0.02787346  0.01992745  0.04069752  0.03860697  0.0445634
    0.01788994  0.02851761 -0.0050432   0.0412723

In [16]:
embedded_docs[0]

print(model.predict(embedded_docs)[0])

[[-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775 -0.0264017
  -0.04175306  0.03438387  0.00483886 -0.01813291]
 [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775 -0.0264017
  -0.04175306  0.03438387  0.00483886 -0.01813291]
 [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775 -0.0264017
  -0.04175306  0.03438387  0.00483886 -0.01813291]
 [-0.01532175 -0.04083961  0.00964322  0.01493043  0.01147775 -0.0264017
  -0.04175306  0.03438387  0.00483886 -0.01813291]
 [-0.04918884  0.03701763 -0.00412145 -0.01944529  0.04716099  0.039835
  -0.01221706 -0.00536225 -0.00781418  0.03370618]
 [-0.0365024  -0.04171776  0.03433042  0.00960976  0.01449699  0.04940602
   0.00861019  0.0392453  -0.00889333 -0.02117573]
 [ 0.00409447 -0.02808121  0.02859398 -0.01169022 -0.02417239 -0.00847627
   0.0374534   0.01881081  0.04700155  0.01323311]
 [ 0.02787346  0.01992745  0.04069752  0.03860697  0.0445634   0.01788994
   0.02851761 -0.0050432   0.04127239  0.02969969]]
